					<div class="row">
							<div class="large-offset-1 columns large-8">

								
								<h1>Termes et conditions</h1>
								<hr>
								
								<div class="row">
										<div class="columns small-12">
											<p>Font generated by <a href="http://www.flaticon.com">flaticon.com</a>
 under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY</a>. The authors are: <a href="http://www.freepik.com">Freepik</a>.</p>
										</div>
									</div>


									
							</div>
						</div>